# Generated by Django 5.0.1 on 2024-02-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('BYBOOK', 'bybook')], max_length=50),
        ),
    ]
