# Generated by Django 5.0.1 on 2024-02-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_books_category_books_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='description',
        ),
        migrations.AddField(
            model_name='books',
            name='details',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
