# Generated by Django 5.0.1 on 2024-02-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category',
            new_name='name',
        ),
    ]
